### ISSUE TITLE
The Approximate Date for Stage II training code

### ISSUE THREAD

**Issue by robot-ai-machinelearning** [changlin31/DS-Net#1]
Hi,

Could you provide the approximate date for releasing the Stage II training code?

**Comment by changlin31** [comment]
Hi, @robot-ai-machinelearning 

I plan to release Stage II code before next Monday, 13 Apr. Thanks for your interest!

**Comment by qgh1223** [comment]
I'm also interested in your stage || code. Hope the code will come soon

**Comment by qgh1223** [comment]
When giving the details of training gate training?

**Comment by qgh1223** [comment]
In the train.py set gate-train?

**Comment by changlin31** [comment]
@qgh1223 
I'm still working on it. Will inform you when I update the code.

**Comment by changlin31** [comment]
@qgh1223 @robot-ai-machinelearning 
Stage II code are released. Thank you.
