### ISSUE TITLE
MAdds of Pretrained Supernet

### ISSUE THREAD

**Issue by LinyeLi60** [changlin31/DS-Net#15]
Hi Changlin, your work is excellent. I have a question about the calculation of MAdds, in README.md the MAdds of `Subnetwork 13` is 565M, but I think the MAdds of `Subnetwork 13`  should be 821M observed in my experiments, because the channel number of `Subnetwork 13` is larger than the original MobileNetV1, and the original MobileNetV1 1.0's MAdds should be 565M. Looking forward to your reply.

**Comment by changlin31** [comment]
Hi, @sixzerotech 
You may have ignored that we always use the smallest channel number (half or less comparing to the original MBNetV1) for the first four stages. More specifically, we use 16, 32, 48, 96 channels for the first 4 stages, whereas MBNetV1 use 32, 64, 128, 256.

**Comment by LinyeLi60** [comment]
Hi Changlin, thank you for your reply, I will close this issue.





------------------ Original ------------------
From: Changlin Li ***@***.***&gt;
Date: Tue,Feb 15,2022 1:33 PM
To: changlin31/DS-Net ***@***.***&gt;
Cc: Linye Li ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [changlin31/DS-Net] MAdds of Pretrained Supernet (Issue #15)





 
Hi, @sixzerotech
 You may have ignored that we always use the smallest channel number (half or less comparing to the original MBNetV1) for the first four stages. More specifically, we use 16, 32, 48, 96 channels for the first 4 stages, whereas MBNetV1 use 32, 64, 128, 256.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
