### ISSUE TITLE
why not set ensemble_ib to True?

### ISSUE THREAD

**Issue by twmht** [changlin31/DS-Net#16]
Hi,

I found that ensemble_ib is set to False for both slim training and gate training from the configs, but from paper it would boost the performance when set toTrue.

Any idea?

**Comment by changlin31** [comment]
In the paper, we perform ablation experiments with MBNet + group norm and find ensemble_ib could stablize training, whereas we finally use BN and find the training is stable enough without ensemble_ib. As ensemble_ib introduces additional training cost and does not consistently yield better result, we set it to False by default. Nevertheless, **if you encountered instability during training, try enable ensemble_ib.**

**Comment by twmht** [comment]
thank you.
