### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by esizikova** [changlin31/DS-Net#3]
Hi, is it possible to release some of the pertained models? Thank you!

**Comment by changlin31** [comment]
Hi, @esizikova @ShengliangD @jianghaojun @sixzerotech

Pretrained MBNet supernet is released here: https://github.com/changlin31/DS-Net/releases/tag/v0.0.1

**Comment by LinyeLi60** [comment]
Thank you very much！





------------------ Original ------------------
From: Changlin Li ***@***.***&gt;
Date: Tue,Nov 30,2021 1:57 PM
To: changlin31/DS-Net ***@***.***&gt;
Cc: 实名冲浪lly ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [changlin31/DS-Net] Pretrained models (#3)
