### ISSUE TITLE
project environment

### ISSUE THREAD

**Issue by singularity97** [changlin31/DS-Net#5]
Hi,could you provide the environment for the project?I try to train the network with python=3.8 pytorch=1.7.1,cuda=10.2.Shortly after starting training,there's a RuntimeError: CUDA error: device-side assert triggered happened,and some other environment also lead to this error.I'm not sure whether the problem is caused by the difference of environment.

**Comment by changlin31** [comment]
Hi,

We only tested our code on CUDA=10.1 and 10.0. You can try python=3.8 pytorch=1.7.1, cuda=10.1.
