### ISSUE TITLE
Why the num_choice in different yml is different?

### ISSUE THREAD

**Issue by chaunceywx** [changlin31/DS-Net#6]
Why you set num_choice in mobilenetv1_bn_uniform_reset_bn.yml as 4, but set this parameter as 14 in the other two yml file?

老哥，如果你也是中国人，咱们还是用中文交流吧，我英语水平比较感人。。。

**Comment by changlin31** [comment]
This arg `num_choice` is only used for evaluation. Now we have set it to 14 for all the experiments. Thanks for the issue!

**Comment by chaunceywx** [comment]
> This arg `num_choice` is only used for evaluation. Now we have set it to 14 for all the experiments. Thanks for the issue!

Thank you for your reply .
