### ISSUE TITLE
UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.

### ISSUE THREAD

**Issue by Chauncey-Wang** [changlin31/DS-Net#8]
Why I get an warning: 
`/home/chauncey/.local/lib/python3.8/site-packages/torchvision/transforms/functional.py:364: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
`
when I use 
`python3 -m torch.distributed.launch --nproc_per_node=1 train.py ./imagenet -c ./configs/mobilenetv1_bn_uniform.yml`

**Comment by changlin31** [comment]
This warning could be caused by the incompatibility of torchvision and pillow. Please provide your version of these two packages.

For reference, we use torchvision=0.8.2 and pillow=6.2.2.

**Comment by Chauncey-Wang** [comment]
> This warning could be caused by the incompatibility of torchvision and pillow. Please provide your version of these two packages.
> 
> For reference, we use torchvision=0.8.2 and pillow=6.2.2.

Thank you for your quick reply.  I use torchvision=0.9.1 and pillow=7.0.0. 
When I change their version as your suggestion, I solve this problem successfully. However, do you know which version of pillow is compatible with torchvision=0.9.1?

**Comment by changlin31** [comment]
Try pillow=6.2.2, I think this works for all the torchvision versions.
